version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: decoapp_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: decoapp
      POSTGRES_PASSWORD: decoapp_secret
      POSTGRES_DB: decoapp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
