import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "@prisma/client";
import * as dotenv from "dotenv";

dotenv.config();

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

const TROPICAL_COUNTRIES = ["CI", "SN", "CM", "BJ", "TG", "GA", "GN", "CG", "CD", "MG"];

async function seedAfricanStyles() {
  const africanStyles = [
    {
      style: "sahel_chic",
      accessoryType: "general",
      suggestions: ["poterie artisanale", "cuivre martelé", "chanvre naturel", "bois de néré"],
      materials: ["cuivre", "argile", "bois léger", "lin naturel", "laiton patiné"],
      colorPalette: ["sable", "beige chaud", "cuivre", "ivoire", "brun doré"],
    },
    {
      style: "wax_moderne",
      accessoryType: "general",
      suggestions: ["tissus wax géométriques", "velours profond", "laiton", "céramique colorée"],
      materials: ["coton wax", "velours", "métal doré", "céramique"],
      colorPalette: ["bleu cobalt", "bordeaux profond", "vert émeraude", "or", "indigo"],
    },
    {
      style: "bantou_minimaliste",
      accessoryType: "general",
      suggestions: ["ébène sculpté", "terre cuite lissée", "raphia tressé", "bronze artisanal"],
      materials: ["ébène", "terre cuite", "raphia", "bronze", "bois iroko"],
      colorPalette: ["noir profond", "terracotta", "blanc cassé", "brun ébène", "ocre rouge"],
    },
    {
      style: "bogolan_urbain",
      accessoryType: "general",
      suggestions: ["tissu bogolan motifs sobres", "coton brut africain", "rotin tressé", "objets recyclés"],
      materials: ["coton bogolan", "jute", "rotin", "cuir végétal", "métal brut"],
      colorPalette: ["noir", "blanc naturel", "ocre jaune", "brun terre", "beige parcheminé"],
    },
  ];

  for (const rule of africanStyles) {
    await prisma.styleRule.upsert({
      where: { style_accessoryType: { style: rule.style, accessoryType: rule.accessoryType } },
      update: rule,
      create: rule,
    });
  }
  console.log(`✓ 4 sous-styles africains seedés`);
}

async function seedAfricanCatalog() {
  const products = [
    // ─── ABIDJAN ───────────────────────────────────────────────────
    {
      id: "abj-tapis-bogolan-01",
      name: "Tapis bogolan tissé main — Grand format",
      type: "tapis",
      styles: ["bogolan_urbain", "bantou_minimaliste"],
      colors: ["noir", "ocre", "blanc"],
      priceFcfa: 95000,
      budgetLevel: "bas",
      description: "Tapis en coton bogolan tissé à la main, motifs géométriques traditionnels. 150×200cm.",
      available: true,
      inStock: true,
      country: "CI",
      city: "Abidjan",
      vendorName: "Atelier Koffi & Fils",
      vendorType: "artisan",
      vendorContactWhatsapp: "+22507000001",
      isHandmade: true,
      localMaterial: "Coton bogolan malien",
      tropicalFriendly: true,
    },
    {
      id: "abj-coussins-wax-01",
      name: "Coussins wax Ankara (lot de 4)",
      type: "coussins",
      styles: ["wax_moderne", "bogolan_urbain"],
      colors: ["bleu cobalt", "bordeaux", "or"],
      priceFcfa: 32000,
      budgetLevel: "bas",
      description: "4 coussins 45×45cm en tissu wax Ankara. Rembourrage polyester anti-humidité.",
      available: true,
      inStock: true,
      country: "CI",
      city: "Abidjan",
      vendorName: "Marché de Treichville — Stand 23",
      vendorType: "marketplace",
      vendorContactWhatsapp: "+22507000002",
      isHandmade: true,
      localMaterial: "Tissu wax hollandais",
      tropicalFriendly: true,
    },
    {
      id: "abj-luminaire-bronze-01",
      name: "Lampe à poser en bronze artisanal",
      type: "luminaire",
      styles: ["sahel_chic", "bantou_minimaliste"],
      colors: ["cuivre", "bronze", "brun"],
      priceFcfa: 78000,
      budgetLevel: "bas",
      description: "Lampe de table en bronze coulé, abat-jour raphia naturel. Hauteur 45cm.",
      available: true,
      inStock: true,
      country: "CI",
      city: "Abidjan",
      vendorName: "Bronzerie Coulibaly",
      vendorType: "artisan",
      vendorContactWhatsapp: "+22507000003",
      isHandmade: true,
      localMaterial: "Bronze et raphia ivoirien",
      tropicalFriendly: false,
    },
    {
      id: "abj-table-iroko-01",
      name: "Table basse en bois Iroko massif",
      type: "table_basse",
      styles: ["bantou_minimaliste", "bogolan_urbain"],
      colors: ["brun", "bois naturel"],
      priceFcfa: 145000,
      budgetLevel: "moyen",
      description: "Table basse rectangulaire en Iroko, bois résistant aux termites. 120×60×40cm.",
      available: true,
      inStock: true,
      country: "CI",
      city: "Abidjan",
      vendorName: "Menuiserie Ébénisterie Yao",
      vendorType: "artisan",
      vendorContactWhatsapp: "+22507000004",
      isHandmade: true,
      localMaterial: "Bois Iroko traité anti-termites",
      tropicalFriendly: true,
    },
    {
      id: "abj-rideaux-wax-01",
      name: "Rideaux en wax géométrique (2 panneaux)",
      type: "rideaux",
      styles: ["wax_moderne"],
      colors: ["indigo", "blanc", "or"],
      priceFcfa: 58000,
      budgetLevel: "bas",
      description: "2 panneaux de rideaux 140×260cm, tissu wax épais, thermique.",
      available: true,
      inStock: true,
      country: "CI",
      city: "Abidjan",
      vendorName: "Tissu Palace Cocody",
      vendorType: "boutique",
      vendorContactWhatsapp: "+22507000005",
      isHandmade: false,
      localMaterial: "Wax imprimé Côte d'Ivoire",
      tropicalFriendly: true,
    },

    // ─── DAKAR ─────────────────────────────────────────────────────
    {
      id: "dkr-tapis-thiebel-01",
      name: "Tapis thiébel brodé — Couleurs sahel",
      type: "tapis",
      styles: ["sahel_chic", "bogolan_urbain"],
      colors: ["sable", "cuivre", "rouge"],
      priceFcfa: 110000,
      budgetLevel: "moyen",
      description: "Tapis en laine thiébel brodé main, motifs géométriques. 160×230cm.",
      available: true,
      inStock: true,
      country: "SN",
      city: "Dakar",
      vendorName: "Atelier Thiès Artisanat",
      vendorType: "artisan",
      vendorContactWhatsapp: "+22170000001",
      isHandmade: true,
      localMaterial: "Laine thiébel du Sénégal",
      tropicalFriendly: false,
    },
    {
      id: "dkr-luminaire-terracotta-01",
      name: "Suspension en terre cuite Sahel",
      type: "luminaire",
      styles: ["sahel_chic", "bantou_minimaliste"],
      colors: ["terracotta", "sable"],
      priceFcfa: 65000,
      budgetLevel: "bas",
      description: "Luminaire suspendu en terre cuite ajourée, effet tamis. Diamètre 35cm.",
      available: true,
      inStock: true,
      country: "SN",
      city: "Dakar",
      vendorName: "Poterie de l'Île de Gorée",
      vendorType: "artisan",
      vendorContactWhatsapp: "+22170000002",
      isHandmade: true,
      localMaterial: "Terre cuite sénégalaise",
      tropicalFriendly: true,
    },
    {
      id: "dkr-coussins-bazin-01",
      name: "Coussins en bazin brodé or (lot de 3)",
      type: "coussins",
      styles: ["wax_moderne", "sahel_chic"],
      colors: ["or", "bordeaux", "vert émeraude"],
      priceFcfa: 45000,
      budgetLevel: "bas",
      description: "3 coussins 40×40cm en bazin riche brodé à la machine. Fermeture éclair.",
      available: true,
      inStock: true,
      country: "SN",
      city: "Dakar",
      vendorName: "Sandaga Tissus & Déco",
      vendorType: "marketplace",
      vendorContactWhatsapp: "+22170000003",
      isHandmade: false,
      localMaterial: "Bazin riche importé et travaillé au Sénégal",
      tropicalFriendly: true,
    },
    {
      id: "dkr-table-calebasse-01",
      name: "Table basse plateau en calebasse laquée",
      type: "table_basse",
      styles: ["sahel_chic", "bogolan_urbain"],
      colors: ["naturel", "laqué noir"],
      priceFcfa: 88000,
      budgetLevel: "bas",
      description: "Table basse avec plateau en calebasse séchée et laquée, pieds en bois de vène. 80×80×35cm.",
      available: true,
      inStock: true,
      country: "SN",
      city: "Dakar",
      vendorName: "Maison Artisanale de Dakar",
      vendorType: "boutique",
      vendorContactWhatsapp: "+22170000004",
      isHandmade: true,
      localMaterial: "Calebasse et bois de vène sénégalais",
      tropicalFriendly: true,
    },
    {
      id: "dkr-objet-mural-01",
      name: "Masque mural en ébène sculpté",
      type: "objet_mural",
      styles: ["bantou_minimaliste", "bogolan_urbain"],
      colors: ["ébène", "noir"],
      priceFcfa: 42000,
      budgetLevel: "bas",
      description: "Masque décoratif sculpté à la main en ébène. Dimensions 25×40cm.",
      available: true,
      inStock: true,
      country: "SN",
      city: "Dakar",
      vendorName: "Galerie Village des Arts",
      vendorType: "boutique",
      vendorContactWhatsapp: "+22170000005",
      isHandmade: true,
      localMaterial: "Ébène du Sénégal",
      tropicalFriendly: false,
    },

    // ─── DOUALA ────────────────────────────────────────────────────
    {
      id: "dla-tapis-raphia-01",
      name: "Tapis en raphia naturel tressé",
      type: "tapis",
      styles: ["bantou_minimaliste", "bogolan_urbain"],
      colors: ["naturel", "brun", "beige"],
      priceFcfa: 75000,
      budgetLevel: "bas",
      description: "Tapis 100% raphia tressé à la main. Résistant à l'humidité. 140×200cm.",
      available: true,
      inStock: true,
      country: "CM",
      city: "Douala",
      vendorName: "Artisanat Bamiléké de l'Ouest",
      vendorType: "artisan",
      vendorContactWhatsapp: "+237600000001",
      isHandmade: true,
      localMaterial: "Raphia du Cameroun",
      tropicalFriendly: true,
    },
    {
      id: "dla-luminaire-rotin-01",
      name: "Lampadaire en rotin et bambou",
      type: "luminaire",
      styles: ["bantou_minimaliste", "wax_moderne"],
      colors: ["naturel", "brun clair"],
      priceFcfa: 55000,
      budgetLevel: "bas",
      description: "Lampadaire 165cm, structure bambou, abat-jour rotin tressé. Anti-humidité.",
      available: true,
      inStock: true,
      country: "CM",
      city: "Douala",
      vendorName: "Rotin & Bambou Cameroun",
      vendorType: "artisan",
      vendorContactWhatsapp: "+237600000002",
      isHandmade: true,
      localMaterial: "Rotin et bambou du Cameroun",
      tropicalFriendly: true,
    },
    {
      id: "dla-coussins-ndop-01",
      name: "Coussins en tissu Ndop royal (lot de 2)",
      type: "coussins",
      styles: ["wax_moderne", "bantou_minimaliste"],
      colors: ["indigo", "blanc", "bleu"],
      priceFcfa: 38000,
      budgetLevel: "bas",
      description: "2 coussins 45×45cm en tissu Ndop authentique, réservé aux royautés bamiléké.",
      available: true,
      inStock: true,
      country: "CM",
      city: "Douala",
      vendorName: "Ndop Tradition — Marché Central",
      vendorType: "marketplace",
      vendorContactWhatsapp: "+237600000003",
      isHandmade: true,
      localMaterial: "Tissu Ndop du Cameroun",
      tropicalFriendly: true,
    },
    {
      id: "dla-table-bois-01",
      name: "Table basse en bois Sapelli massif",
      type: "table_basse",
      styles: ["bantou_minimaliste", "sahel_chic"],
      colors: ["brun rougeâtre", "bois naturel"],
      priceFcfa: 185000,
      budgetLevel: "moyen",
      description: "Table basse en Sapelli du Cameroun, finition huile naturelle. 100×55×38cm.",
      available: true,
      inStock: true,
      country: "CM",
      city: "Douala",
      vendorName: "Menuiserie Fouda & Frères",
      vendorType: "artisan",
      vendorContactWhatsapp: "+237600000004",
      isHandmade: true,
      localMaterial: "Bois Sapelli traité Cameroun",
      tropicalFriendly: true,
    },
    {
      id: "dla-papier-peint-batik-01",
      name: "Papier peint batik artisanal (rouleau 5m)",
      type: "papier_peint",
      styles: ["wax_moderne", "bogolan_urbain"],
      colors: ["indigo", "terracotta", "or"],
      priceFcfa: 45000,
      budgetLevel: "bas",
      description: "Papier peint effet batik fait à la main, résistant humidité tropicale. 52cm de large.",
      available: true,
      inStock: true,
      country: "CM",
      city: "Douala",
      vendorName: "Studio Batik Douala",
      vendorType: "boutique",
      vendorContactWhatsapp: "+237600000005",
      isHandmade: true,
      localMaterial: "Papier traité localement",
      tropicalFriendly: true,
    },
  ];

  for (const item of products) {
    await prisma.accessoryCatalog.upsert({
      where: { id: item.id },
      update: item,
      create: item,
    });
  }
  console.log(`✓ ${products.length} produits africains seedés (Abidjan, Dakar, Douala)`);
}

async function main() {
  console.log("🌍 Seeding localisation Afrique francophone...");
  await seedAfricanStyles();
  await seedAfricanCatalog();
  console.log("✅ Done!");
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
